import repositories.animal_repository as animal_repo
import repositories.vet_repository as vet_repo
import repositories.owner_repository as owner_repo
import repositories.treatment_repository as treatment_repo
import repositories.appointment_repository as appoint_repo
import repositories.A_T_repository as at_repo